### ISSUE TITLE
Handling additional arguments

### ISSUE THREAD

**Issue by nickbabcock** [crate-ci/azure-pipelines#10]
I've been executing with `--all` on cargo components even if the workspace just contains a single package

```
cargo clippy --all
cargo fmt --all
```

Currently `clippy.yml`, `rustfmt.yml`, `warnings.yml` don't support `--all`. While I'd vote for `--all` to be the default behavior, this problem is a subset of handling additional arguments. For instance, maybe I want to execute clippy and fmt with a verbose flag, so maybe a one size fits all won't work here.

I was curious if there has been any thought given to this use case.

**Comment by jonhoo** [comment]
Closing this in favor of #78.
