### ISSUE TITLE
Note parameters at top of document

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#13]
Compare
https://github.com/crate-ci/azure-pipelines/blob/master/azure/install-rust.yml

with
https://github.com/crate-ci/resources/blob/master/az-pipeline/unstable/rustup.yml

The latter is easier to see what can be passed in.

**Comment by jonhoo** [comment]
Ah, yes, `components` was added only recently, and I just didn't remember to also add it to the top.
