### ISSUE TITLE
Is a fix for Linux having rustup needed?

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#14]
This fix went in recently to the crate-ci/resources repo

https://github.com/crate-ci/resources/pull/11

Do we need it?

**Comment by jonhoo** [comment]
Yup, fixed in https://github.com/crate-ci/azure-pipelines/commit/cd785e27cbec19263893377a08efe129151c45d4 + https://github.com/crate-ci/azure-pipelines/commit/3aca61c3350901f10ef925bcbe78703c4a3a3285.
