### ISSUE TITLE
sccache support?

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#16]
> Larger projects/organizations might also want to try using sccache, which doesn't need to load all the cached content initially; it does require an S3 or equivalent setup, though. [Here](https://github.com/rustwasm/wasm-bindgen/blob/13b672aac0445e616dd516bbbbc26230166b7775/ci/azure-install-sccache.yml) is how wasm-bindgen does it.

From [killercup](https://www.reddit.com/r/rust/comments/cc4k9x/rustypipes_easy_continuous_integration_for_rust/eto8kz1/?st=jy1nl9gk&sh=4af4d74d)

**Comment by jonhoo** [comment]
cc @killercup

**Comment by jonhoo** [comment]
Closing this in favor of #78.
