### ISSUE TITLE
For when a `Cargo.lock`, is included, verify that it isn't stale

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#21]
This is a problem I regularly run into.  The most common case is that I update my version and submit it and next time I run cargo, the lock file is changed, making me commit it later.

Ideally, when the `Cargo.lock` is used, we'd use the `--locked` flag to ensure it is correct.

**Comment by jonhoo** [comment]
I think we _probably_ only need to do this in the very first stage (`cargo check`). Shouldn't be _too_ hard to pull off with something like
```bash
[[ -e Cargo.lock ]] && cargo check --locked || cargo check
```
