### ISSUE TITLE
Help people with producing GitHub artifacts

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#23]
For binaries, it is common on tagged releases to upload them to github following a specific pattern to be compatible with gh-install tools, see [trust](https://github.com/japaric/trust)

**Comment by epage** [comment]
One of the problems is we can't offer a pre-built solution because there might be various requirements (legal notification, completion files, etc).  cargo-tarball is meant to help solve that problem but I've not been getting time to finish stager and cargo-tarball.  In the mean time, we might want to at least give an example of how to build and upload a binary on a tagged release.

**Comment by jonhoo** [comment]
I think @Keats' `azure-pipelines.yml` from [over here](https://github.com/Keats/azure-pipelines-test/blob/54cc1d270b66d9ecbf67765d545d97951191ee59/azure-pipelines.yml#L90) may be good inspiration for this.

**Comment by jonhoo** [comment]
There are a number of other GitHub artefacts we may also want to produce. Two good examples are pushing `master` documentation to `gh-pages` and producing GitHub releases. There is some more context over at https://github.com/tokio-rs/tracing/pull/191#issuecomment-512596017.

**Comment by epage** [comment]
I split ghp docs out into #35

**Comment by jonhoo** [comment]
We can probably learn from https://github.com/rustwasm/wasm-bindgen/blob/master/azure-pipelines.yml + https://github.com/rustwasm/wasm-bindgen/tree/master/ci here!

**Comment by jonhoo** [comment]
I think this is now explicitly out-of-scope. If your project wants this, it should write a job that uses the `install-rust` template and then upload the artifact. That said, maybe we want an `examples/` directory that gives example jobs for things like this?

**Comment by jonhoo** [comment]
See also #78.
