### ISSUE TITLE
Cargo check should use `--all-targets`

### ISSUE THREAD

**Issue by jrakow** [crate-ci/azure-pipelines#24]
Currently the cargo check script uses `--bins --examples --tests`
https://github.com/crate-ci/azure-pipelines/blob/0471851e53018eade2a78543e080de9345c67a26/azure/cargo-check.yml#L16
These options are not complete. Benches are missing for example.

`--all-targets` is the better option (https://doc.rust-lang.org/cargo/commands/cargo-check.html).

**Comment by jonhoo** [comment]
It does not use `--all-targets` because it implies `--benches`, which will generally not compile on `stable`/`beta` since `#[bench]` is nightly-only :)

I would love to be able to switch to `--all-targets`, though I think that issue would have to be solved first.

**Comment by epage** [comment]
iirc benches is stable, the harness is not (allowing you to use [criterion](https://bheisler.github.io/criterion.rs/book/getting_started.html)).

However, we are then split on whether to focus on custom harness users or the built-in harness users.

**Comment by jonhoo** [comment]
Sorry, what I mean is that _if_ a binary or library has benchmarks that use the built-in harness, then running `cargo check --all-targets` _will_ fail when using `stable`. This would probably be very unexpected from the author's perspective. I'm not sure what the best way around this is though, because as you say we _would_ like to check things like criterion benchmarks. May be worth filing a cargo issue for this?

**Comment by epage** [comment]
I was just clarifying the situation,  that for some people it can work on stable. As long as we have something step that is ensuring benches compile, I have no problem directly calling out each type of target rather than using `--all-targets`.

**Comment by jonhoo** [comment]
There's this:
https://github.com/crate-ci/azure-pipelines/blob/0471851e53018eade2a78543e080de9345c67a26/azure/cargo-check.yml#L23

Though it's not currently settable from `stages`, and not called out in the `parameters` list at the top of the file, so that should probably be fixed.

**Comment by jrakow** [comment]
I wasn't aware of the issues with nightly. I just remembered that the option `--all-targets` exists and was wondering why it was not used. Thanks for the discussion, I learnt stuff.

**Comment by jonhoo** [comment]
I opened #26 to track the `benches` issue.
