### ISSUE TITLE
Should we verify minimal dependency versions

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#25]
cargo has an unstable flag to calculate dependencies using the minimum rather than the maximum version.  This verifies that `Cargo.toml`s are not stale.

**Comment by epage** [comment]
The downside is the brittleness of dependencies if they aren't also verifying it.

**Comment by jonhoo** [comment]
I think this should be an opt-in stage. Not sure what Rust version it should be run on (does it require nightly atm?).

**Comment by epage** [comment]
I think you can use unstable flags without nightly but I'm unsure.  I at least do it with libtest's json output.

**Comment by epage** [comment]
As for best practices, I am unsure.  I've seen discussions around this but haven't adopted it myself (yet).  I've been tempted to adopt it due to minrust issues.

**Comment by jonhoo** [comment]
Relevant: https://github.com/rust-lang-nursery/api-guidelines/issues/123

**Comment by jonhoo** [comment]
Closing this in favor of #78.
