### ISSUE TITLE
Template for performing release to crates.io

### ISSUE THREAD

**Issue by jonhoo** [crate-ci/azure-pipelines#34]
See https://twitter.com/thramp/status/1151842961648476160.

It'd be neat if certain commits to master (or some particular branch) could automatically trigger `cargo publish` (including for sub-crates).

**Comment by killercup** [comment]
cf. https://github.com/rustwasm/wasm-bindgen/blob/2529bb0b17b9153b7904f7a8cc43acef301f29ff/azure-pipelines.yml#L291

**Comment by epage** [comment]
[cargo-release](https://github.com/sunng87/cargo-release) takes care of all of the little things and has workspace support.  sunng87/cargo-release#117 is working to come up with what an auto-release workflow would look like.

**Comment by jonhoo** [comment]
I wonder what running `cargo-release` from CI would look like. In some sense I wonder if CI should _just_ do the publishing, and not the git-related stuff. Basically, *you* tag a commit as a release, and then CI does the rest.

**Comment by epage** [comment]
> I wonder what running cargo-release from CI would look like. In some sense I wonder if CI should just do the publishing, and not the git-related stuff. Basically, you tag a commit as a release, and then CI does the rest.

`cargo-release` is fairly configurable so we could possibly define configurations for it that split the two sides.  One of the oddities is if you tag, update versionss and update dependencies all within the same commit or do you let it bubble up?

**Comment by jonhoo** [comment]
I think this is now explicitly out-of-scope. If your project wants this, it should write a job that uses the `install-rust` template and then does `cargo release`.

**Comment by jonhoo** [comment]
See also #78.
