### ISSUE TITLE
Support for uploading documentation to ghp

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#35]
@jonhoo in #23 

> There are a number of other GitHub artefacts we may also want to produce. Two good examples are pushing `master` documentation to `gh-pages` and producing GitHub releases. There is some more context over at https://github.com/tokio-rs/tracing/pull/191#issuecomment-512596017.

**Comment by epage** [comment]
For uploading as part of a pipeline, [cargo-ghp-upload](https://crates.io/crates/cargo-ghp-upload) might be able to help.

An alternative is to instead upload when cutting a release using [cargo-release](https://crates.io/crates/cargo-ghp-upload)

**Comment by jonhoo** [comment]
I think this is now explicitly out-of-scope. If your project wants this, it should write a job that uses the `install-rust` template and then builds the necessary resources.

**Comment by jonhoo** [comment]
See also #78.
