### ISSUE TITLE
Allow tweaking Rust version for coverage job

### ISSUE THREAD

**Issue by djc** [crate-ci/azure-pipelines#37]
rustc has been broken for a while for Quinn's coverage. This has recently been fixed on master, so it would be nice if I can tweak the config to have coverage run on nightly instead of stable.

**Comment by epage** [comment]
Looks like there is a [`latest-nightly` tag](https://hub.docker.com/r/xd009642/tarpaulin/tags) we could take advantage of.

Questions to resolve for this
- How to expose this in [`coverage.yml` template](https://github.com/crate-ci/azure-pipelines/blob/master/azure/coverage.yml)?  Do we accept the docker information as a parameter?  Accept the rusttoolchain and map that to docker images?
- Should this be exposed in [`stages.yml` template](https://github.com/crate-ci/azure-pipelines/blob/master/azure/stages.yml) or is it too specialized, making the usability worse for the simple cases?

@jonhoo, thoughts?

**Comment by djc** [comment]
I was thinking just as a parameter. My particular use may indeed be quite niche, but I could imagine that nightly-only projects (for example, anyone working on their async/await stuff right now) would still be interested in coverage data, so just defaulting to stable doesn't seem like a great option either.

**Comment by jonhoo** [comment]
#42 adds a `nightly_coverage` parameter to `stages`, and `nightly` parameter to `coverage` :)
