### ISSUE TITLE
tarpaulin failures don't show up as errors

### ISSUE THREAD

**Issue by djc** [crate-ci/azure-pipelines#39]
In the job below, tarpaulin failed (see also #37) but reports as successful:

https://dev.azure.com/quinn-rs/Quinn/_build/results?buildId=7&view=logs&s=0ffffa8c-a783-570b-868c-b44a3db2ace1

This is bad because no coverage updates are submitted, but this might not be obvious.

**Comment by djc** [comment]
(See also: https://github.com/xd009642/tarpaulin/issues/219.)

**Comment by epage** [comment]
That is strange.  We're not doing anything to tell Azure to ignore the failure.

**Comment by djc** [comment]
No, this is really a tarpaulin bug. Just useful to be aware of and potentially something we could work around here?

**Comment by jonhoo** [comment]
I think this is now resolved? Please re-open if I am wrong :)
