### ISSUE TITLE
Support installing programs uploaded to github releases

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#4]
- [x] Bash support (stolen from trust)
- [ ] Powershell support (being ported from trust)
- [ ] Documentation
- [ ] Azure Pipeline templates
- [ ] Tests

Note: install scripts independent of Azure Pipelines is an important deliverable for this.  The goal is to provide tools to support people with whatever CI they are using.  Wrapping the scripts with a step template or task is providing improved integration for one CI that at least supports such work.  If other CIs had similar features and someone wants to work on it, that would still be within scope.  This is not an AzDO-specific project.

**Comment by epage** [comment]
Scripts are at https://github.com/crate-ci/gh-install

**Comment by jonhoo** [comment]
Closing this in favor of #78.
