### ISSUE TITLE
Optionally run ignored tests

### ISSUE THREAD

**Issue by djc** [crate-ci/azure-pipelines#41]
In Quinn, we have one test which we `ignore`, so that we don't run it locally; but we do want to run it in CI. Would be nice if this was supported in the stages templates (as a parameter?).

This basically involves passing `--ignored` to `cargo test`.

https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested

**Comment by jonhoo** [comment]
#42 adds a `test_ignored` parameter to `stages`, `tests`, and `test`. I also added `single_threaded` should you want to run your tests with `--test-threads=1`.
