### ISSUE TITLE
Document procedure for injecting custom environment setup

### ISSUE THREAD

**Issue by Ralith** [crate-ci/azure-pipelines#45]
For example, for openxrs I need libXxf86vm and libXrandr installed on Linux machines (but not elsewhere). Maybe this is more of a general azure pipelines question, but a pointer to the pertinent docs would be helpful if so.

e: Looks like there's something with `parameters.setup`? It's not immediately obvious what reasonable settings for it might look like, though.

**Comment by jonhoo** [comment]
Yup, `parameters.setup` is for this exact purpose! I've started writing docs in #43, and there you'll find a section on [additional setup steps](https://github.com/crate-ci/azure-pipelines/blob/5187c3bb00675d9ee0f55e9b6d06a8b50d2f3ad1/docs/configuration.md#additional-setup-steps). Is that along the lines you were thinking?

**Comment by Ralith** [comment]
Yeah, thanks!

**Comment by jonhoo** [comment]
I think this is now resolved? Please re-open if I am wrong :)
