### ISSUE TITLE
rustup takes too long on Azure

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#5]
40s-2m.  That is a large percentage of some jobs' runtime

**Comment by epage** [comment]
They are testing a fix for this in rustup 1.20!
https://www.reddit.com/r/rust/comments/d5hbdu/rustup_needs_your_help_testing_a_new_feature/?st=k0nyagh5&sh=be7ac9ab

**Comment by jonhoo** [comment]
We now install `rustup` with `--profile minimal`, which fixes this issue!
