### ISSUE TITLE
It is possible to use VS2017?

### ISSUE THREAD

**Issue by Geobert** [crate-ci/azure-pipelines#54]
I've seen that we use `windows-2019` as vmImage. Is there a way to override this to use VS2017 (windows-2019 seems to use VS2019)?

**Comment by jonhoo** [comment]
Do you mean when using `stages.yml`? No, there isn't currently. Out of curiosity, why do you specifically need VS2017? Does your project work on macOS and Linux?

**Comment by Geobert** [comment]
I'm a `cobalt.rs` contributor and we have an issue atm with `onig` not compiling on VS2019. I also had issues with `sass-sys`.

**Comment by jonhoo** [comment]
Interesting... I'm a little hesitant to add three new parameters to `stages.yml`, `tests.yml`, *and* `test.yml` to set the `vmImage` to use for linux, macos, and windows though. @epage what do you think?

**Comment by epage** [comment]
I'm mixed (I also am the maintainer of cobalt).

Cobalt's CI is a bit slow as-is so I'm thinking of experimenting with hand writing all the jobs to tune the CIs performance, only reusing the install step.  This will let us bypass the problem.

**Comment by Geobert** [comment]
So there's no need to add these params for now (it was for cobalt)
