### ISSUE TITLE
Document (implement?) support for nightly/beta-only crates

### ISSUE THREAD

**Issue by Ralith** [crate-ci/azure-pipelines#58]
We're trying to move Quinn master to async/await without losing CI. Is this supported at all? I don't see any likely looking parameters except for coverage.

**Comment by jonhoo** [comment]
@Ralith see #59 :) It doesn't support also checking on `beta`, but given that crates should be in `beta+nightly` for a relatively short period of time, I don't think it's worth adding a special case for that. If you feel strongly about it you can also use `nightly-stages.yml` and then add your own stage which also tests on beta.
