### ISSUE TITLE
cargo-check fails on workspaces due to --no-default-features

### ISSUE THREAD

**Issue by qdot** [crate-ci/azure-pipelines#66]
--no-default-features errors on workspace projects, meaning the cargo-check step will fail for any workspace project. It'd be nice to have a parameter to turn this build check off. 

See https://github.com/rust-lang/cargo/issues/5015

**Comment by jonhoo** [comment]
@epage I think more and more that we need either a workspace flag, or a separate workspace stage :'(

**Comment by qdot** [comment]
I submitted a small workaround PR for now. It could be used for configuring a workspace stage if you do go that direction.

**Comment by epage** [comment]
> @epage I think more and more that we need either a workspace flag, or a separate workspace stage :'(

Are all crates safe with "no-default-features`?  Would we need it configurable anyways, like all-features?

**Comment by jonhoo** [comment]
See also https://github.com/rust-lang/cargo/issues/7727
