### ISSUE TITLE
Using Windows/MacOS for rust azure-pipelines

### ISSUE THREAD

**Issue by qdot** [crate-ci/azure-pipelines#68]
It looks like the cargo-check stage is hardwired to use the ubuntu platform. I've got code that will be using core foundation on MacOS and WinRT/UWP on windows via rust, and would like to be able to build these systems concurrently on azure pipelines. Is that out of scope for this project, or just currently unimplemented?

**Comment by jonhoo** [comment]
Windows and MacOS are both run during the test stage. The idea here was that the check stage should be as fast as possible to root out unnecessary builds, and then we run the full test suite afterwards. Does that not work for your needs?

**Comment by qdot** [comment]
Ah, got it. That'd be fine, yeah. I just missed the "cross" parameter on the tests. :)
